name: Github Page with Sveltekit

permissions:
  pages: write
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy with node 12 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with: 
        persist-credentials: false
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: 16

    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
    - name: Setup pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: '.'
    - name: Deploy to github pages
      id: deployment
      uses: actions/deploy-pages@v1
