name: Github Page with Sveltekit

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy with node 12 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with: 
        persist-credentials: false
    - name: Use Node.js 16
      uses: actions/setup-node@master
      with:
        node-version: 16

    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build
