name: Github Page with Sveltekit

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy with node 12 and ubuntu-latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: 12

    - name: npm install, build and test
      run: |
        npm install
        npm run build
